enum TOKENS {
    ZEROTOKEN,
    PLUS, MINUS, MULTIPLY, DIVIDE, POWER,
    LESS, GREATER, LESSEQUAL, GREATEREQUAL,
    PLUSINF, MINUSINF, UNIF, 
    EXP, LN, SIN, COS, TAN, COTAN, TOZA,
    OKRSKOB, ZKRSKOB, OKVSKOB, ZKVSKOB,
    REALNUMBER, IKS
};
